# Generated by Django 5.2.5 on 2025-08-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/uploads/'),
        ),
    ]
